id: AE4D99BD4
title: A Prayer to Tārā
type: translation
pechas:
- I95379444
- IE1AFEFA1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:54.198755
  last_modified_at: 2023-01-04 11:27:54.198761
  collections:
  - Alak Zenkar Pema Ngödrup Rolwe Dorje
  - Works of Tibetan Masters
alignment_to_base:
  I95379444/BD4C: 07F0
  IE1AFEFA1/A06E: 07F0
